# .rubocop.yml

Layout/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 120

Metrics/BlockLength:
  Max: 120

Metrics/AbcSize:
  Max: 35

Naming/AccessorMethodName:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/MultilineBlockChain:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'app/controllers/specific_controller.rb' 
    - 'config/environments/development.rb'
    - 'config/routes.rb'
    - 'db/schema.rb'
