version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: huy@123456
      MYSQL_DATABASE: sample_db
      MYSQL_USER: app_test
      MYSQL_PASSWORD: huy@123456
    ports:
      - "3306:3306"  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  web:
    container_name: app_test
    build: .
    volumes:
      - ".:/app_test"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://localhost:6379
      DB_USER: root
      DB_NAME: sample_db
      DB_PASSWORD: huy@123456
      DB_HOST: localhost
